# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='picture',
            field=models.ImageField(default='', upload_to='pictures'),
        ),
    ]
