# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='picture',
        ),
    ]
