# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20180703_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/wards/%Y/%m/%d'),
        ),
    ]
