# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20180705_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/offices/%Y/%m/%d'),
        ),
    ]
