# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20180728_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
