# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0004_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/counties/%Y/%m/%d'),
        ),
    ]
