# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, unique_for_date='published'),
        ),
    ]
